# EDA Covid

### 1. Data

##### 1-1. data load

In [1]:
import pandas as pd

data = r"C:\Users\jjjun_ii\Documents\GitHub\LIKELION_AI\Data_TIL\EDA\data\owid-covid-data.csv"
df = pd.read_csv(data)
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN

In [5]:
df.shape

(192301, 67)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192301 entries, 0 to 192300
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    192301 non-null  object
 1   continent                                   181123 non-null  object
 2   location                                    192301 non-null  object
 3   date                                        192301 non-null  object
 4   total_cases                                 184750 non-null  float64
 5   new_cases                                   184508 non-null  float64
 6   new_cases_smoothed                          183334 non-null  float64
 7   total_deaths                                166260 non-null  float64
 8   new_deaths                                  166241 non-null  float64
 9   new_deaths_smoothed                         165078 non-null  float64
 10  total_cases_per_million                     183898 non-null  float64
 11  new_cases_per_million                       183656 non-null  float64
 12  new_cases_smoothed_per_million              182487 non-null  float64
 13  total_deaths_per_million                    165421 non-null  float64
 14  new_deaths_per_million                      165402 non-null  float64
 15  new_deaths_smoothed_per_million             164244 non-null  float64
 16  reproduction_rate                           143384 non-null  float64
 17  icu_patients                                25581 non-null   float64
 18  icu_patients_per_million                    25581 non-null   float64
 19  hosp_patients                               26818 non-null   float64
 20  hosp_patients_per_million                   26818 non-null   float64
 21  weekly_icu_admissions                       6252 non-null    float64
 22  weekly_icu_admissions_per_million           6252 non-null    float64
 23  weekly_hosp_admissions                      12463 non-null   float64
 24  weekly_hosp_admissions_per_million          12463 non-null   float64
 25  total_tests                                 77796 non-null   float64
 26  new_tests                                   74090 non-null   float64
 27  total_tests_per_thousand                    77796 non-null   float64
 28  new_tests_per_thousand                      74090 non-null   float64
 29  new_tests_smoothed                          101500 non-null  float64
 30  new_tests_smoothed_per_thousand             101500 non-null  float64
 31  positive_rate                               93607 non-null   float64
 32  tests_per_case                              91844 non-null   float64
 33  tests_units                                 104285 non-null  object
 34  total_vaccinations                          52725 non-null   float64
 35  people_vaccinated                           50207 non-null   float64
 36  people_fully_vaccinated                     47700 non-null   float64
 37  total_boosters                              24777 non-null   float64
 38  new_vaccinations                            43231 non-null   float64
 39  new_vaccinations_smoothed                   104052 non-null  float64
 40  total_vaccinations_per_hundred              52725 non-null   float64
 41  people_vaccinated_per_hundred               50207 non-null   float64
 42  people_fully_vaccinated_per_hundred         47700 non-null   float64
 43  total_boosters_per_hundred                  24777 non-null   float64
 44  new_vaccinations_smoothed_per_million       104052 non-null  float64
 45  new_people_vaccinated_smoothed              102973 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  102973 non-null  float64
 47  stringency_index                            149839 non-null  float64
 48  population                                  191132 non-null  float64
 49  population_density                          171353 non-null  float64
 50  median_age                                  158825 non-null  float64
 51  aged_65_older                               157142 non-null  float64
 52  aged_70_older                               157992 non-null  float64
 53  gdp_per_capita                              157971 non-null  float64
 54  extreme_poverty                             103125 non-null  float64
 55  cardiovasc_death_rate                       158461 non-null  float64
 56  diabetes_prevalence                         166210 non-null  float64
 57  female_smokers                              119852 non-null  float64
 58  male_smokers                                118209 non-null  float64
 59  handwashing_facilities                      77857 non-null   float64
 60  hospital_beds_per_thousand                  140598 non-null  float64
 61  life_expectancy                             179837 non-null  float64
 62  human_development_index                     154377 non-null  float64
 63  excess_mortality_cumulative_absolute        6553 non-null    float64
 64  excess_mortality_cumulative                 6553 non-null    float64
 65  excess_mortality                            6553 non-null    float64
 66  excess_mortality_cumulative_per_million     6553 non-null    float64
dtypes: float64(62), object(5)
memory usage: 98.3+ MB